module_name: HalloweenCountdown
compatible_versions: 1.0.0+
author: Michael Rouse
category: front office
tags:
  - countdown
  - halloween
description_short: Add a Halloween countdown to your store footer
description: description.md
license: MIT
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
